openapi: 3.1.0
x-stoplight:
  id: qm51c0rvx8k8y
info:
  title: CarRent
  version: '1.0'
  summary: CarRent API Documentation
servers:
  - url: 'http://localhost/api/v1'
paths:
  /login:
    post:
      summary: Login
      tags:
        - Auth
      responses:
        '200':
          $ref: '#/components/responses/LoginResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
      operationId: Login
      requestBody:
        $ref: '#/components/requestBodies/LoginRequest'
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Accept
  /logout:
    post:
      summary: ''
      operationId: Logout
      responses:
        '204':
          description: No Content
      security:
        - BearerToken: []
      x-internal: false
      tags:
        - Auth
    parameters: []
  /user:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: User
      security:
        - BearerToken: []
  /register:
    post:
      summary: ''
      operationId: Register
      requestBody:
        $ref: '#/components/requestBodies/RegisterRequest'
      tags:
        - Auth
      responses:
        '201':
          $ref: '#/components/responses/RegisterResponse'
        '422':
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas: {}
  securitySchemes:
    BearerToken:
      name: Bearer
      type: apiKey
      in: header
  requestBodies:
    LoginRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
          examples:
            Example 1:
              value:
                email: admin@admin.admin
                password: Admin123.
      description: Request Body for login
    RegisterRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              last_name:
                type: string
              email:
                type: string
              password:
                type: string
              password_confirmation:
                type: string
              phone_number:
                type: string
  responses:
    LoginResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  access_token:
                    type: string
                  user_id:
                    type: string
    RegisterResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: number
                      attributes:
                        type: object
                        properties:
                          name:
                            type: string
                          last_name:
                            type: string
                          full_name:
                            type: string
                          email:
                            type: string
              success:
                type: boolean
    ErrorResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              error_code:
                type: integer
              success:
                type: boolean
            x-examples:
              Example 1:
                error: The email has already been taken.
                error_code: 422
                success: false
x-internal: false
